version: "3.4"
services:
  app: 
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prdapp
    image: "gcr.io/${GOOGLE_PROJECT_ID}/stmnews"
    environment:
      - APP_ENV=local
    ports: 
      - "8080:8080"
