version: "3.4"
services:
  app: 
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prdapp
    image: "us-west2-docker.pkg.dev/${GOOGLE_PROJECT_ID}/uw2-repo/stmnews"
    environment:
      - APP_ENV=local
    ports: 
      - "8080:8080"
